name: PrismaCloud Scan
on:
  workflow_call: 
    secrets:
      PCC_CONSOLE_URL:
        description: "PrismaCloud Console URL"
        required: true
      PCC_USER:
        required: true
        description: "PrismaCloud API KEY"
      PCC_PASS:
        required: true
        description: "PrismaCloud API TOKEN"
      PAT_GITHUB_TOKEN:
        required: true
        description: Github Token

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  PrismaScan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_GITHUB_TOKEN }}
        
    - name: Build a Docker image
      run: docker build . --tag $IMAGE_NAME

    - name: Prisma Cloud image scan
      id: scan
      uses: PaloAltoNetworks/prisma-cloud-scan@v1
      with:
        pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
        pcc_user: ${{ secrets.PCC_USER }}
        pcc_pass: ${{ secrets.PCC_PASS }}
        image_name: ${{ env.IMAGE_NAME }} 